[project]
name = "open-rppg"
version = "0.1.0"
requires-python = ">=3.9,<=3.12"

[tool.setuptools]
packages = {find = {}}
include-package-data = true

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
